### ISSUE TITLE
Server reply option to not json encode result

### ISSUE THREAD

**Issue by chriskapp** [datto/php-json-rpc#12]
Hi, I have a use case where I need to get the output as PHP value, means not encoded as json. Currently in the reply method of the server the output is always encoded as json see (https://github.com/datto/php-json-rpc/blob/master/src/Server.php#L70). What do you think about adding a new argument i.e. `$encode = true` which determines whether we encode the output or not? If you like I could create an PR for this.

**Comment by smortensen** [comment]
Hey Chris,

Would you be open to a phone call? I'd like to understand that use case and hear your proposal.

Here's my contact information:
http://spencermortensen.com/contact/

I'm free most of the day on Tuesday or Wednesday. If you're up for it, send me a text, and we'll go from there.

~Spencer

**Comment by ghost** [comment]
> Hi, I have a use case where I need to get the output as PHP value, means not encoded as json. Currently in the reply method of the server the output is always encoded as json see (https://github.com/datto/php-json-rpc/blob/master/src/Server.php#L70). What do you think about adding a new argument i.e. `$encode = true` which determines whether we encode the output or not? If you like I could create an PR for this.

But this is a json rpc  "I'm crying here))"

**Comment by chriskapp** [comment]
Hi @smortensen thanks for the feedback, sure we can schedule a call but Iam mostly available on weekend, my timezone is UTC+1. Otherwise the use case exists only since I have embedded the JsonRPC server in a system where the JSON de/encoding happens outside. As a workaround I currently simply json_decode the response but in this case it would be faster to get the raw response.

@gfijrb sorry I dont understand your point.

**Comment by smortensen** [comment]
Hi @chriskapp,

I _almost_ have enough information, but I'd like to understand that use case better. Is it an open-source project? Is there any way I could take a quick look at the source code?

I know this a ton of work for such a simple change. I just wanted to say that I want to help, and I'm on your side! I just want to see in what way I can help the most.

~Spencer

**Comment by chriskapp** [comment]
Yes, no problem, so Iam working on Fusio which is an open source API management system https://github.com/apioo/fusio
You can see the current implementation at:
https://github.com/apioo/fusio-impl/blob/master/src/Export/Api/JsonRpc.php#L150

If I think about it we could also save us this argument if you could make the methods `processInput`, `processRequest` and `processBatchRequests` protected instead of private. Then I could create my custom server implementation extending the default server, where I could adjust the json encode/decode behaviour.

**Comment by smortensen** [comment]
Yes, we could do that.

It sounds like you're implementing a tweaked version of JSON-RPC? This library follows the narrow specifications and you'd like to go beyond that? But, to do it, you need to revert the JSON encoding applied by this library, patch the underlying data structures, and then re-apply the whole JSON encoding when you're done?

Did I understand it correctly? If that's right, then _naturally_ you'd be looking for changes to the underlying library to make it all efficient. In that case, it sounds very reasonable to make those methods protected for you.

**Comment by smortensen** [comment]
All right, I made an untagged commit that should give us an easier starting point for further changes. I've separated the JSON encoding from the rest of the logic:
https://github.com/datto/php-json-rpc/commit/85eceaecab8e078077de440627b7fe504db951b6

At this point, your derived class would need to call `processInput` and override `processRequest`--is that right? Is there anything else you would like?

**Comment by chriskapp** [comment]
Hi, thanks for your effort. So for my case I would need to overwrite the method `reply` to simply remove the `json_encode` from the `$output` and at the `getInput` method I would need to remove the `json_decode`. So the json encoding/decoding simply happens outside of the JsonRPC server otherwise it should work exactly the same.

**Comment by smortensen** [comment]
In case anyone else needs this functionality, the 6.1.0 release adds new public methods that allow you to extend and tweak the JSON-RPC format.
