### ISSUE TITLE
Implementation::isValidCode($code) bug

### ISSUE THREAD

**Issue by koliesnik** [datto/php-json-rpc#6]
https://github.com/datto/php-json-rpc/blob/597e946ab364c52ad114e717d3b482367c847f8d/src/Exception/Implementation.php#L92
`return is_int($code) && (-32000 <= $code) && ($code <= -32099);`
should be changed to 
`return is_int($code) && (-32099 <= $code) && ($code <= -32000);`
because the original condition is never true

**Comment by smortensen** [comment]
Wow, I wasn't expected that there were any bugs in the codebase. Thank you for finding that range issue!

I've released a new version (4.0.4) with your fix:
https://github.com/datto/php-json-rpc/commit/0f4b4e574d83ecda2cd0819afddc3003f923f804

~Spencer
